// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2avAmnYRjdrY82X9V4X54p-bg7gPUuaI',
    appId: '1:272134060432:web:c3e29abdb000d9d0325b15',
    messagingSenderId: '272134060432',
    projectId: 'susma-47e3b',
    authDomain: 'susma-47e3b.firebaseapp.com',
    storageBucket: 'susma-47e3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDEifzrPX2d-tAT1urM8wrx0RVlDAi3Yo',
    appId: '1:272134060432:android:58e2be6e2ee17cd3325b15',
    messagingSenderId: '272134060432',
    projectId: 'susma-47e3b',
    storageBucket: 'susma-47e3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt32YuzyiEwcen5XIA9MehBUK8qs7FsCA',
    appId: '1:272134060432:ios:ef212c17d3e89a7e325b15',
    messagingSenderId: '272134060432',
    projectId: 'susma-47e3b',
    storageBucket: 'susma-47e3b.firebasestorage.app',
    iosBundleId: 'com.example.susma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt32YuzyiEwcen5XIA9MehBUK8qs7FsCA',
    appId: '1:272134060432:ios:ef212c17d3e89a7e325b15',
    messagingSenderId: '272134060432',
    projectId: 'susma-47e3b',
    storageBucket: 'susma-47e3b.firebasestorage.app',
    iosBundleId: 'com.example.susma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2avAmnYRjdrY82X9V4X54p-bg7gPUuaI',
    appId: '1:272134060432:web:ecbd1877e59554dc325b15',
    messagingSenderId: '272134060432',
    projectId: 'susma-47e3b',
    authDomain: 'susma-47e3b.firebaseapp.com',
    storageBucket: 'susma-47e3b.firebasestorage.app',
  );
}
